import assert from 'node:assert/strict';
import { recommendedBid, validateBidRules, propertyNumber } from '../src/lib/recommendedBid';
import { parseGoogleProperty, googlePropertyPrompt } from '../src/lib/googleProperty';
const rules = [{id:'higher', maxSalePrice:800000, rate:0.06},{id:'lower',maxSalePrice:500000,rate:0.05}];
const imported = parseGoogleProperty('• Last Sale Price: $500,000\n• Square Footage: 2,500 square feet\n• County: Maricopa\n• Address: 19833 East Raven Drive');
assert.equal(recommendedBid(imported.fields, rules).amount, 125);
assert.equal(recommendedBid({...imported.fields,salePrice:'$500,001'},rules).amount,150);
assert.equal(recommendedBid({...imported.fields,salePrice:'$800,001'},rules).amount,null);
assert.equal(recommendedBid({...imported.fields,salePrice:'Not found'},rules).amount,null);
assert.equal(recommendedBid({...imported.fields,squareFootage:'2,500–2,700'},rules).amount,null);
assert.equal(recommendedBid(imported.fields,[]).amount,null);
assert.equal(recommendedBid(imported.fields,JSON.parse(JSON.stringify(rules))).amount,125,'Workspace JSON round trip preserves rules');
assert.equal(recommendedBid(imported.fields,[{...rules[1],rate:0.06123}]).amount,153.08);
assert.equal(propertyNumber('$500,000 (sold in 2022)','money'),null);
assert.equal(propertyNumber('250,00','money'),null);
assert.equal(propertyNumber('2,500 sq. ft.','area'),2500);
assert.ok(validateBidRules([rules[0],{...rules[0],id:'duplicate'}]));
assert.ok(validateBidRules([{...rules[0],rate:0}]));
assert.ok(validateBidRules([{...rules[0],maxSalePrice:NaN}]));
assert.equal(validateBidRules([]),null);
assert.equal(recommendedBid({salePrice:'N/A',estimatedValue:'500000',squareFootage:'2500'},rules).amount,null);
assert.equal(recommendedBid(parseGoogleProperty('Last Sale Price: $400,000\nLast Sale Price: $600,000\nSquare Footage: 2500').fields,rules).amount,null);
assert.equal(parseGoogleProperty('Last Sale Price: Not found').fields.salePrice,undefined);
const prompt=googlePropertyPrompt('19833 East Raven Drive, Queen Creek, AZ 85142');
assert.ok(prompt.includes('template: Last Sale Price: | Address:'));
assert.ok(prompt.includes('| Square Footage:'));
assert.ok(!/formula|formual|\[\]/i.test(prompt));
console.log('Bid checks passed: inclusive thresholds, ordering, rounding, missing/ambiguous values, validation, JSON persistence shape and Google prompt/import.');

assert.equal(recommendedBid(imported.fields,[{...rules[1],rate:0.06}]).amount,150,'Same saved data recalculates with updated rules without a new import');
